export const seedIncidents = [
  ['INC-001','payments-api','P1','v3.4.2','Payment requests returned 502 after deployment.','connection acquisition timeout; pool active=20 max=20','Database connection pool exhaustion','Increased connection pool from 20 to 50','Restarting application pods did not help','For 502 plus connection acquisition timeouts, inspect pool saturation before restarting services.'],
  ['INC-004','orders-api','P2','v2.8.1','Checkout latency climbed above 12 seconds.','slow query detected on orders_status_idx','Missing database index','Added composite index for customer_id and status','Increased pod replicas without impact','Slow query incidents need query-plan review before horizontal scaling.'],
  ['INC-007','auth-service','P1','v8.2.0','Users could not sign in after a configuration deployment.','REDIS_CONNECTION_TIMEOUT','Redis connection limit reached','Raised Redis maxclients and enabled client pooling','Rolled back the auth container image','For Redis timeouts, check connection limits and client pool behavior.'],
  ['INC-009','catalog-api','P2','v5.1.0','Product pages intermittently returned 503.','upstream timed out after 3000ms','Third-party inventory API timeout','Added circuit breaker and cached last successful inventory response','Raised request timeout only','Protect dependency calls with timeouts, fallbacks, and a circuit breaker.'],
  ['INC-011','payments-api','P2','v3.3.8','Payment authorization requests slowed after a traffic campaign.','too many connections for role payments','Database maximum connections reached','Reserved a pool for payments and reduced idle connection lifetime','Restarted the database client','Track pool usage separately from database-wide connection limits.'],
  ['INC-014','billing-worker','P2','v1.9.4','Invoice jobs failed immediately after release.','missing environment variable BILLING_REGION','Incorrect environment variable','Restored BILLING_REGION in deployment configuration','Retried failed jobs before fixing configuration','Compare required environment variables before retrying deployment failures.'],
  ['INC-016','checkout-web','P1','v6.0.0','Checkout requests returned 500 after rollout.','TypeError: currencyRules undefined','Version incompatibility between web and pricing SDK','Pinned pricing SDK to compatible version','Scaled web instances','Validate dependency compatibility in the release candidate.'],
  ['INC-018','inventory-api','P2','v4.5.6','Inventory reads became stale and slow.','redis used_memory peak; evicted_keys 18401','Redis memory pressure','Increased maxmemory and changed eviction policy to allkeys-lru','Flushed cache during peak traffic','Memory pressure needs capacity and eviction policy review before cache flushes.'],
  ['INC-021','shipping-api','P2','v2.1.9','Carrier labels failed for a subset of requests.','429 rate limit exceeded','Carrier API rate limiting','Added queued retries with exponential backoff','Retried immediately in a loop','Respect provider quotas and use bounded exponential backoff.'],
  ['INC-023','search-api','P3','v7.1.3','Search indexing fell behind after catalog import.','process RSS 3.8GB; OOMKilled','Worker memory exhaustion','Reduced batch size and added memory ceiling','Added more concurrent workers','Bound batch size before adding concurrency to memory-bound workloads.'],
  ['INC-026','orders-api','P1','v2.7.7','Order placement deadlocked under flash-sale traffic.','deadlock detected; transaction rolled back','Database transaction deadlock','Changed lock ordering and added bounded retry','Raised database connection pool','Deadlocks require lock-order analysis; pool size does not remove contention.'],
  ['INC-028','gateway','P1','v1.14.0','Several downstream services showed 502 responses.','upstream connect error to service-discovery','Service discovery dependency failure','Restored unhealthy discovery nodes and enabled quorum alerts','Restarted every downstream service','Trace shared dependencies before restarting affected services.'],
  ['INC-031','payments-api','P2','v3.4.0','Payment API connections failed during peak traffic.','FATAL remaining connection slots reserved','Connection limit reached','Reduced pool idle lifetime and increased database capacity','Increased HTTP retry count','Connection limits require pool tuning and capacity planning.'],
  ['INC-034','notifications-api','P3','v2.3.1','Webhook deliveries returned unauthorized responses.','401 invalid audience claim','OAuth audience configuration mismatch','Updated webhook audience configuration','Regenerated an unrelated API key','Match OAuth audience and issuer configuration across services.'],
  ['INC-038','catalog-api','P2','v5.3.0','Catalog API CPU reached 96 percent after deployment.','hot path JSON serialization 78% CPU','Deployment regression in serialization path','Reverted serializer and added response caching','Added more CPU limits','Profile a new CPU spike before scaling the service.']
].map(([id, service, severity, deployment, description, logs, rootCause, resolution, failedAttempts, lesson], index) => ({
  id, service, severity, deployment, description, logs, rootCause, resolution, failedAttempts,
  investigation: 'Reviewed service logs, recent deployment changes, dependency health, and relevant telemetry.',
  outcome: 'Resolved and service health returned to normal.', lesson, status: 'resolved', memoryUsed: false,
  createdAt: new Date(Date.now() - (15 - index) * 86400000).toISOString(), resolvedAt: new Date(Date.now() - (15 - index) * 86400000 + 7200000).toISOString()
}));

export function experienceText(incident) {
  return `INCIDENT EXPERIENCE\nIncident: ${incident.id}\nService: ${incident.service}\nDeployment: ${incident.deployment || 'unknown'}\nSymptoms: ${incident.description}\nLogs: ${incident.logs || 'not supplied'}\nInvestigation: ${incident.investigation || 'not supplied'}\nFailed approach: ${incident.failedAttempts || 'not supplied'}\nRoot cause: ${incident.rootCause || 'not yet determined'}\nSuccessful resolution: ${incident.resolution || 'not yet determined'}\nOutcome: ${incident.outcome || 'not supplied'}\nLesson: ${incident.lesson || 'not supplied'}`;
}
